Repository MamaNyoSquad/mamanyosquad.github.io, pull requests merged in 2023-07, with the labels that each got.

#201 Maintenance Details updated for Japanese Edition
  index.html
  maintenance/index.html
  scripts/maintenance.js
Labels: DEPLOY, MINOR, MAINTENANCE

#202 tbmassoc attribute at the footer must need a title in its `<a>`
  404.html
  anniversary/index.html
  archive/20230505.html
  archive/20230506.html
  archive/index.html
  blog/20221229/index.html
  blog/20230416/index.html
  blog/index.html
  events/index.html
  index.html
  kt-disclosure/index.html
  maintenance/index.html
  policies/index.html
Labels: DEPLOY, MINOR

#203 changed url from `20210707` to `20210907`
  publishing/index.html
  publishing/insidestory-20210907/index.html
Labels: DEPLOY, MINOR

#204 minor change to meet the immersion in `vidiaries-app`
  publishing/insidestory-20210907/index.html
Labels: DEPLOY, MINOR

#205 Maintenance Details updated for Global Edition
  maintenance/index.html
  scripts/maintenance.js
Labels: DEPLOY, MINOR, MAINTENANCE

#206 inside story viewer updated
  css/insidestory.css
  publishing/insidestory-20210907/index.html
Labels: DEPLOY, MINOR

#208 Branch Merge
  publishing/insidestory/20211119_1.html
Labels: MERGE

#209 two more Inside Stories migrated to website
  publishing/index.html
  publishing/insidestory/20211031.html
  publishing/insidestory/20211119_1.html
  publishing/insidestory/20211119_2.html
  publishing/insidestory/20220130.html
Labels: MAJOR, DEPLOY, PUBLISHING

#210 symbol changes
  publishing/insidestory/20211119_2.html
  publishing/insidestory/20220130.html
Labels: DEPLOY, MINOR

#212 major updates and maintenance
  404.html
  anniversary/1anniv/index.html
  anniversary/2anniv/index.html
  anniversary/index.html
  archive/20220505.html
  archive/20220509.html
  archive/20220604.html
  archive/20220708.html
  archive/20220908.html
  archive/20230505.html
  archive/20230506.html
  archive/index.html
  blog/20221120/index.html
  blog/20221229/index.html
  blog/20230416/index.html
  blog/index.html
  events/index.html
  index.html
  kt-disclosure/index.html
  maintenance/index.html
  policies/index.html
  publishing/app/index.html
  publishing/index.html
  publishing/insidestory/20210907.html
  publishing/insidestory/20210920.html
  publishing/insidestory/20211031.html
  publishing/insidestory/20211119_1.html
  publishing/insidestory/20211119_2.html
  publishing/insidestory/20220130.html
  scripts/maintenance.js
  style.css
Labels: MAJOR, DEPLOY, MAINTENANCE

#213 Maintenance Details for Japanese Edition
  css/maintenancestatus.css
  maintenance/index.html
  scripts/maintenance.js
Labels: MAJOR, DEPLOY, MAINTENANCE
