Repository MamaNyoSquad/mamanyosquad.github.io, pull requests merged in 2023-03, with the labels that each got.

#137 Maintenance Routines under Queue
  maintenance/index.html
Labels: DEPLOY, MINOR, MAINTENANCE

#138 Branch Merge
  anniversary/index.html
  archive/index.html
  css/homefeed.css
  index.html
  maintenance/index.html
  policies/index.html
  publishing/index.html
Labels: MERGE

#140 merge merge
  maintenance/index.html
Labels: MERGE

#142 QUICK COMMIT: updated Japanese branding term
  kt-disclosure/index.html
Labels: DEPLOY, MINOR, MERGE

#143 event header removal and maintenance for both editions
  anniversary/index.html
  archive/index.html
  index.html
  maintenance/index.html
  policies/index.html
  publishing/index.html
Labels: DEPLOY, MINOR, MAINTENANCE

#141 merge merge
  anniversary/index.html
  archive/index.html
  index.html
  kt-disclosure/index.html
  maintenance/index.html
  policies/index.html
  publishing/index.html
Labels: MERGE

#145 merge merge
  maintenance/index.html
Labels: MERGE

#146 invocation of the Venus Island Diaries App
  css/publishing.css
  css/vidiaries-app.css
  media/images/vidiaries-app/v0.2.8-prerelease/lang.png
  media/images/vidiaries-app/v0.2.8-prerelease/mainStoryButton.png
  media/images/vidiaries-app/v0.2.8-prerelease/mit.png
  media/images/vidiaries-app/v0.2.8-prerelease/oneUI.png
  media/images/vidiaries-app/v0.2.8-prerelease/splash.png
  media/images/vidiaries-app_head.png
  media/images/vidiaries-app_icon.png
  media/svg/MIT.svg
  media/svg/gfonts/android.svg
  media/svg/gfonts/info.svg
  media/svg/github.svg
  media/svg/vidiaries_icon.svg
  media/svg/vidiaries_logo.svg
  publishing/app/index.html
  publishing/index.html
Labels: MAJOR, DEPLOY, PUBLISHING

#147 merge merge
  publishing/app/index.html
Labels: MERGE

#148 Venus Island Diaries is now Kotlin-First (`v0.3.0-prerelease`)
  media/images/vidiaries-app/v0.3.0-prerelease/kotlinFirst.png
  publishing/app/index.html
Labels: DEPLOY, MINOR, PUBLISHING

#149 merge merge
  publishing/app/index.html
Labels: MERGE

#150 merge merge
  publishing/app/index.html
Labels: MERGE

#151 merge merge
  maintenance/index.html
Labels: MERGE

#152 merge merge
  maintenance/index.html
Labels: MERGE

#144 merge merge
  css/publishing.css
  css/vidiaries-app.css
  maintenance/index.html
  media/images/vidiaries-app/v0.2.8-prerelease/lang.png
  media/images/vidiaries-app/v0.2.8-prerelease/mainStoryButton.png
  media/images/vidiaries-app/v0.2.8-prerelease/mit.png
  media/images/vidiaries-app/v0.2.8-prerelease/oneUI.png
  media/images/vidiaries-app/v0.2.8-prerelease/splash.png
  media/images/vidiaries-app/v0.3.0-prerelease/kotlinFirst.png
  media/images/vidiaries-app_head.png
  media/images/vidiaries-app_icon.png
  media/svg/MIT.svg
  media/svg/gfonts/android.svg
  media/svg/gfonts/info.svg
  media/svg/github.svg
  media/svg/vidiaries_icon.svg
  media/svg/vidiaries_logo.svg
  publishing/app/index.html
  publishing/index.html
Labels: MERGE
